# todo fix the workflow so the app gets deployed automatically

# .github/workflows/deploy.yml
name: Deploy HSS tool to Google Cloud Run
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploying ğŸš€ HSS tool
    runs-on: ubuntu-latest
#    if: "contains(github.event.head_commit.message, 'bump version')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Build and push image to Google Container Registry
      - name: Setting up
        uses: google-github-actions/setup-gcloud@v0
        with:
          version: '286.0.0'
          service_account_key: ${{ secrets.GCP_SA_KEY_JSON }}
          service_account_email: "hhri.usyd@gmail.com"
          project_id: heat-stress-scale

      - name: Building (ğŸ—ï¸)
        run: |-
          gcloud builds submit \
            --tag gcr.io/heat-stress-scale/hss-web-app

      # Setup gcloud CLI
      - name: Deploy (ğŸš€)
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: hss-web-app
          image: gcr.io/heat-stress-scale/hss-web-app
          region: us-central1
          credentials: ${{ secrets.GCP_SA_KEY_JSON }}
          project_id: heat-stress-scale